# Generated by Django 3.2.7 on 2021-11-30 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('calenderLink', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=511)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='NewsImages/')),
                ('body', models.TextField()),
                ('post_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='exclusiveImages/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exclusiveVids/')),
                ('caption', models.CharField(max_length=511)),
                ('body', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
