# Generated by Django 3.2.7 on 2021-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholderOne', models.CharField(max_length=255)),
                ('cardholderTwo', models.CharField(max_length=255)),
                ('LookupID', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('MemberID', models.CharField(max_length=255)),
                ('MemberSince', models.CharField(max_length=255)),
                ('ValidThrough', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='link',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
