# Generated by Django 3.2.7 on 2021-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0002_auto_20211105_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='exclusiveImages/'),
        ),
    ]
