# Generated by Django 3.2.7 on 2021-11-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0006_auto_20211106_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calenderLink', models.CharField(max_length=511)),
            ],
        ),
    ]
