# Generated by Django 3.2.7 on 2021-11-18 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0007_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
